### ISSUE TITLE
Changing the default port on out-of-the-box install

### ISSUE THREAD

**Issue by fouasnon** [camunda/docs.camunda.org#54]
Hello,
I'm trying to change the default port that gets used when I run the `start-camunda.sh` script on an out-of-the-box install, but I haven't been able to configure it differently.

I tried rgrepping the `conf` dir for port `8080` and changing all the values that match but that didn't seem to work.  

Additionally, I can't seem to find and kill the process using `ps aux | grep <search-terms>`.  I was thinking maybe it was still running and didn't reload the configuration.

I would love to see a little hint in the documentation about changing port configurations.  (In my case, I'd love to know how to do that with the out-of-the-box install.)  Any advice would be appreciated.  Thank you.

(Btw, I'm running ubuntu 14.04 and running camunda from my home dir with the `start-camunda.sh` script.)

**Comment by meyerdan** [comment]
Tanks you for this feedback and sorry for not replying sooner we were busy with our latest minor release.

I suppose you are using Apache Tomcat?
I found a [short article which explains how to set the port in Tomcat](http://www.mkyong.com/tomcat/how-to-change-tomcat-default-port/).

You should be able to find the  tomcat process using `ps -aux | grep tomcat`

Daniel
